### ISSUE TITLE
Site migration

### ISSUE THREAD

**Issue by jayhesselberth** [rnabioco/molb-7950#1]
Import content from:

- [ ] https://github.com/MOLB7621/workshop/
- [ ] https://github.com/IDPT7810/practical-data-analysis
- [ ] https://github.com/srinivasramachandran/Anschutz_python

**Comment by jayhesselberth** [comment]
@nmukherjee where is the content for your R course?

**Comment by nmukherjee** [comment]
https://github.com/sjaganna/molb7910 <https://github.com/sjaganna/molb7910>
