### ISSUE TITLE
Data for single cell problem sets lives in another repository

### ISSUE THREAD

**Issue by taliaferrojm** [rnabioco/molb-7950#30]
Data for those problem sets lives here: https://github.com/rnabioco/molb-7950-data/tree/main/block-rna/scrnaseq/data

It's not necessarily a problem, but you have to make sure that that data gets into the Posit cloud assignment. It would be simpler if it was in this repository, that way it automatically gets uploaded to posit when we make the template assignment.

**Comment by jayhesselberth** [comment]
This is by design so as not to bloat this repo. Added a note to the README in df6d4c21fad24714423728701df8d9deb9c1cdb5
