### ISSUE TITLE
no key for problem set 32

### ISSUE THREAD

**Issue by taliaferrojm** [rnabioco/molb-7950#32]

**Comment by jayhesselberth** [comment]
@kwells4 do you have a key for this problem set? It's the second single-cell set.

**Comment by kwells4** [comment]
This was all Kent's that I just dropped in to teach this year. I don't know where he would have the key.

**Comment by jayhesselberth** [comment]
@kriemo would you by chance happen to have the key to this problem set?

**Comment by kriemo** [comment]
The key is likely on my laptop but i'm away traveling and don't have it with me right now. I'll check when I'm back on the 27th.

**Comment by kriemo** [comment]
I can't find this key. I believe the last time we assigned a problem set for the second lecture was fall 2020. It was most likely shared via slack or might be available on canvas. The content in the ps-32 .Rmd is also out of date with the content presented in the slides (the problem set uses Seurat, but the slides present using Bioconductor).

**Comment by jayhesselberth** [comment]
No problem, thanks for checking. I'm going to open a separate issue to track this.
